sections_data = [
    {
        "section": "CCIS3A",
        "names": [
            {"first_name": "Paolo", "last_name": "Bautista"},
            {"first_name": "Haeng Si", "last_name": "Baek"},
            {"first_name": "Micah Joyce", "last_name": "Cabaltea"},
            {"first_name": "Kyle Chester", "last_name": "Castañeda"},
            {"first_name": "Daniel Eligio", "last_name": "Catalla"},
            {"first_name": "Jared", "last_name": "Daclizon"},
            {"first_name": "Vince Randall", "last_name": "David"},
            {"first_name": "Christian John", "last_name": "Diwa"},
            {"first_name": "Alyssa Mae", "last_name": "Espina"},
            {"first_name": "Curtis Anthony", "last_name": "Fenderson"},
            {"first_name": "Jhonn Reille", "last_name": "Frane"},
            {"first_name": "Mark Lawrence", "last_name": "Garcia"},
            {"first_name": "Christian Dale", "last_name": "Gopez"},
            {"first_name": "Raziel", "last_name": "Guiao"},
            {"first_name": "Oborowari", "last_name": "Kime"},
            {"first_name": "Jerome", "last_name": "Lictaoa"},
            {"first_name": "Kholeen Nicole", "last_name": "Lopez"},
            {"first_name": "Josh Patrick Riley", "last_name": "Maglalang"},
            {"first_name": "Lian Angela", "last_name": "Meneses"},
            {"first_name": "Aldrin", "last_name": "Nunag"},
            {"first_name": "Jennel Gabriel", "last_name": "Ong"},
            {"first_name": "Luige", "last_name": "Pasion"},
            {"first_name": "Angelah Jhane", "last_name": "Pettus"},
            {"first_name": "Theodore Carlo", "last_name": "Radam"},
            {"first_name": "Trisha", "last_name": "Salas"},
            {"first_name": "John Cedric", "last_name": "Sicat"},
            {"first_name": "Kyla Anne", "last_name": "Sunga"},
            {"first_name": "Christian", "last_name": "Tiglao"},
            {"first_name": "Chrisha", "last_name": "Tuazon"},
            {"first_name": "Alexandra Maris", "last_name": "Yambao"},
        ],
        "subjects": [
            {
                "subject_code": "IML",
                "subject_name": "Information Management (Lab)",
                "units": 3,
                "instructor": {"first_name": "Jhulyna Mae", "last_name": "Rubio"},
            },
            {
                "subject_code": "PROG3L",
                "subject_name": "Object-Oriented Programming (Lab)",
                "units": 3,
                "instructor": {"first_name": "Ralph", "last_name": "Cadalzo"},
            },
            {
                "subject_code": "CPC",
                "subject_name": "Purposive Communication",
                "units": 3,
                "instructor": {"first_name": "Consuelo", "last_name": "Gregorio"},
            },
            {
                "subject_code": "PATHFIT 3",
                "subject_name": "Physical Activities Toward Health and Fitness 3",
                "units": 2,
                "instructor": {"first_name": "Relly Rose", "last_name": "Tobias"},
            },
            {
                "subject_code": "OSL",
                "subject_name": "Operating Systems (Lab)",
                "units": 3,
                "instructor": {"first_name": "Harold Jacob", "last_name": "Henthorn"},
            },
            {
                "subject_code": "IPS",
                "subject_name": "Indigenous People's Studies",
                "units": 3,
                "instructor": {"first_name": "Jay Mark", "last_name": "Tiatco"},
            },
            {
                "subject_code": "SYAD",
                "subject_name": "System Analysis and Design",
                "units": 3,
                "instructor": {"first_name": "Gabriela", "last_name": "Rashid"},
            },
            {
                "subject_code": "ETL",
                "subject_name": "Application Development and Emerging Technologies (Lab)",
                "units": 3,
                "instructor": {"first_name": "Mark Anthony", "last_name": "Madalipay"},
            },
        ],
    },
    {
        "section": "CCIS3B",
        "names": [
            {"first_name": "Andrew", "last_name": "Smith"},
            {"first_name": "Benjamin", "last_name": "Brown"},
            {"first_name": "Charlie", "last_name": "Jones"},
            {"first_name": "Diana", "last_name": "Wilson"},
            {"first_name": "Emily", "last_name": "Taylor"},
            {"first_name": "Frank", "last_name": "Moore"},
            {"first_name": "Grace", "last_name": "Anderson"},
            {"first_name": "Hannah", "last_name": "Thomas"},
            {"first_name": "Isabella", "last_name": "Jackson"},
            {"first_name": "James", "last_name": "White"},
            {"first_name": "Katherine", "last_name": "Harris"},
            {"first_name": "Liam", "last_name": "Martin"},
            {"first_name": "Mason", "last_name": "Thompson"},
            {"first_name": "Nora", "last_name": "Garcia"},
            {"first_name": "Oscar", "last_name": "Martinez"},
            {"first_name": "Paige", "last_name": "Roberts"},
            {"first_name": "Quinn", "last_name": "Young"},
            {"first_name": "Ryan", "last_name": "Walker"},
            {"first_name": "Sophie", "last_name": "Allen"},
            {"first_name": "Travis", "last_name": "King"},
            {"first_name": "Uma", "last_name": "Scott"},
            {"first_name": "Victor", "last_name": "Nelson"},
            {"first_name": "Will", "last_name": "Carter"},
            {"first_name": "Xander", "last_name": "Mitchell"},
            {"first_name": "Yara", "last_name": "Perez"},
            {"first_name": "Zoe", "last_name": "Evans"},
        ],
        "subjects": [
            {
                "subject_code": "IML",
                "subject_name": "Information Management (Lab)",
                "units": 3,
                "instructor": {"first_name": "Jhulyna Mae", "last_name": "Rubio"},
            },
            {
                "subject_code": "PROG3L",
                "subject_name": "Object-Oriented Programming (Lab)",
                "units": 3,
                "instructor": {"first_name": "Ralph", "last_name": "Cadalzo"},
            },
            {
                "subject_code": "CPC",
                "subject_name": "Purposive Communication",
                "units": 3,
                "instructor": {"first_name": "Consuelo", "last_name": "Gregorio"},
            },
            {
                "subject_code": "PATHFIT 3",
                "subject_name": "Physical Activities Toward Health and Fitness 3",
                "units": 2,
                "instructor": {"first_name": "Relly Rose", "last_name": "Tobias"},
            },
            {
                "subject_code": "OSL",
                "subject_name": "Operating Systems (Lab)",
                "units": 3,
                "instructor": {"first_name": "Harold Jacob", "last_name": "Henthorn"},
            },
            {
                "subject_code": "IPS",
                "subject_name": "Indigenous People's Studies",
                "units": 3,
                "instructor": {"first_name": "Jay Mark", "last_name": "Tiatco"},
            },
            {
                "subject_code": "SYAD",
                "subject_name": "System Analysis and Design",
                "units": 3,
                "instructor": {"first_name": "Gabriela", "last_name": "Rashid"},
            },
            {
                "subject_code": "ETL",
                "subject_name": "Application Development and Emerging Technologies (Lab)",
                "units": 3,
                "instructor": {"first_name": "Harold Jacob", "last_name": "Henthorn"},
            },
        ],
    },
]
